workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 120
    integrations:
      # !!! ИСПРАВЛЕНО: Теперь имя точно совпадает с твоим ключом !!!
      app_store_connect: Codemagic Fresh
    environment:
      node: 22
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g ios-deploy
          gem install cocoapods xcodeproj
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Setup Capacitor iOS
        script: |
          rm -rf ios
          npx cap add ios
          npx cap sync ios
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            pod install
          fi

      - name: Fetch Signing Files
        script: |
          # Используем v2 чтобы сбросить глючные старые сертификаты
          keychain initialize
          app-store-connect fetch-signing-files "com.x5pro.app.v2" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: 💎 Force Link Profile (Ruby Hack)
        script: |
          ruby -r xcodeproj -e '
            require "date"
            profiles_dir = File.expand_path("~/Library/MobileDevice/Provisioning Profiles")
            profile_path = Dir["#{profiles_dir}/*.mobileprovision"].max_by { |f| File.mtime(f) }
            
            if profile_path.nil?
              puts "❌ ОШИБКА: Профиль не найден!"
              exit 1
            end
            
            uuid = File.read(profile_path).match(/<key>UUID<\/key>\s*<string>(.*?)<\/string>/)[1]
            puts "✅ UUID профиля: #{uuid}"
            
            project_path = "ios/App/App.xcodeproj"
            project = Xcodeproj::Project.open(project_path)
            
            project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings["DEVELOPMENT_TEAM"] = "F8LA8PC4U6"
                # ВАЖНО: ID совпадает с v2
                config.build_settings["PRODUCT_BUNDLE_IDENTIFIER"] = "com.x5pro.app.v2"
                config.build_settings["CODE_SIGN_STYLE"] = "Manual"
                config.build_settings["CODE_SIGN_IDENTITY"] = "iPhone Distribution"
                config.build_settings["PROVISIONING_PROFILE"] = uuid
                config.build_settings["PROVISIONING_PROFILE_SPECIFIER"] = uuid
              end
            end
            project.save
          '

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true